// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entities.Entities
{
    public partial class tbAutores
    {
        public tbAutores()
        {
            tbLibros = new HashSet<tbLibros>();
        }

        public int auto_Id { get; set; }
        public string auto_Nombre { get; set; }
        public string auto_Apellido { get; set; }
        public int? Pais_Id { get; set; }
        public DateTime? auto_fecha_nacimiento { get; set; }
        public int? auto_UsuarioCreacion { get; set; }
        public DateTime? auto_FechaCreacion { get; set; }
        public int? auto_UsuarioModificacion { get; set; }
        public DateTime? auto_FechaModificacion { get; set; }

        public virtual tbPaises Pais { get; set; }
        public virtual tbUsuarios auto_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios auto_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbLibros> tbLibros { get; set; }
    }
}