// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entities.Entities
{
    public partial class tbPaises
    {
        public tbPaises()
        {
            tbAutores = new HashSet<tbAutores>();
        }

        public int Pais_Id { get; set; }
        public string Pais_Descripcion { get; set; }
        public int? Pais_UsuarioCreacion { get; set; }
        public DateTime? Pais_FechaCreacion { get; set; }
        public int? Pais_UsuarioModificacion { get; set; }
        public DateTime? Pais_FechaModificacion { get; set; }

        public virtual tbUsuarios Pais_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Pais_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbAutores> tbAutores { get; set; }
    }
}