// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsua_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsua_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbAutoresauto_UsuarioCreacionNavigation = new HashSet<tbAutores>();
            tbAutoresauto_UsuarioModificacionNavigation = new HashSet<tbAutores>();
            tbGenerosGene_UsuarioCreacionNavigation = new HashSet<tbGeneros>();
            tbGenerosGene_UsuarioModificacionNavigation = new HashSet<tbGeneros>();
            tbLibrosLibr_UsuarioCreacionNavigation = new HashSet<tbLibros>();
            tbLibrosLibr_UsuarioModificacionNavigation = new HashSet<tbLibros>();
            tbPaisesPais_UsuarioCreacionNavigation = new HashSet<tbPaises>();
            tbPaisesPais_UsuarioModificacionNavigation = new HashSet<tbPaises>();
        }

        public int Usua_Id { get; set; }
        public string Usua_Nombre { get; set; }
        public string Usua_Contrasena { get; set; }
        public int? Usua_UsuarioCreacion { get; set; }
        public DateTime? Usua_FechaCreacion { get; set; }
        public int? Usua_UsuarioModificacion { get; set; }
        public DateTime? Usua_FechaModificacion { get; set; }

        public virtual tbUsuarios Usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbAutores> tbAutoresauto_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbAutores> tbAutoresauto_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbGeneros> tbGenerosGene_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbGeneros> tbGenerosGene_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbLibros> tbLibrosLibr_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbLibros> tbLibrosLibr_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPaises> tbPaisesPais_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPaises> tbPaisesPais_UsuarioModificacionNavigation { get; set; }
    }
}