// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Entities.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Practica.DataAcces;

namespace Practica.DataAcces.Context
{
    public partial class PlantillaContext : DbContext
    {
        public PlantillaContext()
        {
        }

        public PlantillaContext(DbContextOptions<PlantillaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbAutores> tbAutores { get; set; }
        public virtual DbSet<tbGeneros> tbGeneros { get; set; }
        public virtual DbSet<tbLibros> tbLibros { get; set; }
        public virtual DbSet<tbPaises> tbPaises { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tbAutores>(entity =>
            {
                entity.HasKey(e => e.auto_Id)
                    .HasName("PK__tbAutore__8C1A040061420385");

                entity.ToTable("tbAutores", "General");

                entity.Property(e => e.auto_Apellido)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.auto_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.auto_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.auto_Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.auto_fecha_nacimiento).HasColumnType("date");

                entity.HasOne(d => d.Pais)
                    .WithMany(p => p.tbAutores)
                    .HasForeignKey(d => d.Pais_Id)
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("FK__tbAutores__Pais___2C3393D0");

                entity.HasOne(d => d.auto_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbAutoresauto_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.auto_UsuarioCreacion)
                    .HasConstraintName("FK_auto_UsuarioCreacion");

                entity.HasOne(d => d.auto_UsuarioModificacionNavigation)
                    .WithMany(p => p.tbAutoresauto_UsuarioModificacionNavigation)
                    .HasForeignKey(d => d.auto_UsuarioModificacion)
                    .HasConstraintName("FK_auto_UsuarioModificacion");
            });

            modelBuilder.Entity<tbGeneros>(entity =>
            {
                entity.HasKey(e => e.Gene_Id)
                    .HasName("PK__tbGenero__87A341461D48A3B4");

                entity.ToTable("tbGeneros", "General");

                entity.Property(e => e.Gene_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Gene_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Gene_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Gene_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbGenerosGene_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Gene_UsuarioCreacion)
                    .HasConstraintName("FK_Generos_UsuarioCreacion");

                entity.HasOne(d => d.Gene_UsuarioModificacionNavigation)
                    .WithMany(p => p.tbGenerosGene_UsuarioModificacionNavigation)
                    .HasForeignKey(d => d.Gene_UsuarioModificacion)
                    .HasConstraintName("FK_Generos_UsuarioModificacion");
            });

            modelBuilder.Entity<tbLibros>(entity =>
            {
                entity.HasKey(e => e.Libr_id)
                    .HasName("PK__tbLibros__49A0ABDCA187C0D6");

                entity.ToTable("tbLibros", "General");

                entity.Property(e => e.Libr_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Libr_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Libr_titulo)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.HasOne(d => d.Gene)
                    .WithMany(p => p.tbLibros)
                    .HasForeignKey(d => d.Gene_Id)
                    .HasConstraintName("FK_Libr_Gene_Id");

                entity.HasOne(d => d.Libr_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbLibrosLibr_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Libr_UsuarioCreacion)
                    .HasConstraintName("FK_Libr_UsuarioCreacion");

                entity.HasOne(d => d.Libr_UsuarioModificacionNavigation)
                    .WithMany(p => p.tbLibrosLibr_UsuarioModificacionNavigation)
                    .HasForeignKey(d => d.Libr_UsuarioModificacion)
                    .HasConstraintName("FK_Libr_UsuarioModificacion");

                entity.HasOne(d => d.auto)
                    .WithMany(p => p.tbLibros)
                    .HasForeignKey(d => d.auto_Id)
                    .HasConstraintName("FK__tbLibros__auto_I__4AB81AF0");
            });

            modelBuilder.Entity<tbPaises>(entity =>
            {
                entity.HasKey(e => e.Pais_Id)
                    .HasName("PK__tbPaises__6356B833B6BE2A58");

                entity.ToTable("tbPaises", "General");

                entity.Property(e => e.Pais_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Pais_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Pais_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Pais_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbPaisesPais_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Pais_UsuarioCreacion)
                    .HasConstraintName("FK_Pais_UsuarioCreacion");

                entity.HasOne(d => d.Pais_UsuarioModificacionNavigation)
                    .WithMany(p => p.tbPaisesPais_UsuarioModificacionNavigation)
                    .HasForeignKey(d => d.Pais_UsuarioModificacion)
                    .HasConstraintName("FK_Pais_UsuarioModificacion");
            });

            modelBuilder.Entity<tbUsuarios>(entity =>
            {
                entity.HasKey(e => e.Usua_Id)
                    .HasName("PK__tbUsuari__E863C8EEC83373BC");

                entity.ToTable("tbUsuarios", "Acceso");

                entity.Property(e => e.Usua_Contrasena)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Usua_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Usua_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Usua_Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.Usua_UsuarioCreacionNavigation)
                    .WithMany(p => p.InverseUsua_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Usua_UsuarioCreacion)
                    .HasConstraintName("FK_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Usua_UsuarioModificacionNavigation)
                    .WithMany(p => p.InverseUsua_UsuarioModificacionNavigation)
                    .HasForeignKey(d => d.Usua_UsuarioModificacion)
                    .HasConstraintName("FK_Usua_UsuarioModificacion");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}